Update ftp-wp-install

diff --git a/ftp-wp-install b/ftp-wp-install
--- a/ftp-wp-install
+++ b/ftp-wp-install
@@ -1,68 +1,96 @@
-#!/bin/bash
+#!/bin/sh
+clear
+echo "============================================"
+echo "WordPress Install Script"
+echo "============================================"
+echo "Do you need to setup new MySQL database? (y/n)"
+read -e setupmysql
+if [ "$setupmysql" == y ] ; then
+	echo "MySQL Admin User: "
+	read -e mysqluser
+	echo "MySQL Admin Password: "
+	read -s mysqlpass
+	echo "MySQL Host (Enter for default 'localhost'): "
+	read -e mysqlhost
+		mysqlhost=${mysqlhost:-localhost}
+fi
+echo "WP Database Name: "
+read -e dbname
+echo "WP Database User: "
+read -e dbuser
+echo "WP Database Password: "
+read -s dbpass
+echo "WP Database Table (Enter for default 'wp_'): "
+read -e dbtable
+	dbtable=${dbtable:-wp_}
+echo "Last chance - sure you want to run the install? (y/n)"
+read -e run
+if [ "$run" == y ] ; then
+	if [ "$setupmysql" == y ] ; then
+		echo "============================================"
+		echo "Setting up the database."
+		echo "============================================"
+		#login to MySQL, add database, add user and grant permissions
+		dbsetup="create database $dbname;GRANT ALL PRIVILEGES ON $dbname.* TO $dbuser@$mysqlhost IDENTIFIED BY '$dbpass';FLUSH PRIVILEGES;"
+		mysql -u $mysqluser -p$mysqlpass -e "$dbsetup"
+		if [ $? != "0" ]; then
+			echo "============================================"
+			echo "[Error]: Database creation failed. Aborting."
+			echo "============================================"
+			exit 1
+		fi
+	fi
+	curl -T $FILE -u $USERNAME:$PASSWORD $SERVER/$DIR
 
-#set -x
-umount /home/$client/web/$site/public_html/wp-content/uploads
-echo '-';
-echo '========================== umounted /home/$client/web/$site/public_html/wp-content/uploads Successfully! =================================';
-echo '-';
-if [ -d /home/$client/web/$site/tmp ]; then echo 'tmp Exists';
+cd $DIR
+	echo "============================================"
+	echo "Installing WordPress for you."
+	echo "============================================"
+	#download wordpress
+	echo "Downloading..."
+	curl -O https://wordpress.org/latest.tar.gz
+	#unzip wordpress
+	echo "Unpacking..."
+	tar -zxf latest.tar.gz
+	#move /wordpress/* files to this dir
+	echo "Moving..."
+	mv wordpress/* ./
+	echo "Configuring..."
+	#create wp config
+	cp wp-config-sample.php wp-config.php
+	#set database details with perl find and replace
+	perl -pi -e "s/database_name_here/$dbname/g" wp-config.php
+	perl -pi -e "s/username_here/$dbuser/g" wp-config.php
+	perl -pi -e "s/password_here/$dbpass/g" wp-config.php
+	perl -pi -e "s/wp_/$dbtable/g" wp-config.php
+	#set WP salts
+	perl -i -pe'
+	  BEGIN {
+	    @chars = ("a" .. "z", "A" .. "Z", 0 .. 9);
+	    push @chars, split //, "!@#$%^&*()-_ []{}<>~\`+=,.;:/?|";
+	    sub salt { join "", map $chars[ rand @chars ], 1 .. 64 }
+	  }
+	  s/put your unique phrase here/salt()/ge
+	' wp-config.php
+	#create uploads folder and set permissions
+	mkdir wp-content/uploads
+	chmod 775 wp-content/uploads
+	echo "Cleaning..."
+	#remove wordpress/ dir
+	rmdir wordpress
+	#remove zip file
+	rm latest.tar.gz
+	#remove bash script if it exists in this dir
+	[[ -f "$file" ]] && rm "wp.sh"
+	echo "========================="
+	echo "[Success]: Installation is complete."
+	echo "========================="
 else
-  echo 'tmp Not Exist'; fi
-rm -rf /home/$client/web/$site/tmp*
-mkdir /home/$client/web/$site/tmp
-
-if [ -f /home/$client/web/$site/public_html/wp-config.php ]; then echo 'wp-config.php Exists';
-mv -f /home/$client/web/$site/public_html/wp-config.php /home/$client/web/$site/tmp
-else
-  echo 'wp-config.php Not Exist'; fi
-if [ -d /home/$client/web/$site/public_html/wp-content ]; then echo 'wp-content Exists';
-mv -f /home/$client/web/$site/public_html/wp-content /home/$client/web/$site/tmp
-cd /home/$client/web/$site/tmp
-tar -zcvf wp-content.tar.gz wp-content 
-else
-  echo 'wp-content Not Exist'; fi
-rm -rf /home/$client/web/$site/public_html* 
-  
-mkdir /home/$client/web/$site/public_html
-
-if [ -f /home/$client/web/$site/tmp/wp-config.php ]; then echo 'wp-config.php Backup Exists, Restoring...';
-mv -f /home/$client/web/$site/tmp/wp-config.php /home/$client/web/$site/public_html/
-else
-  echo ''; fi
-  
-cd /home/$client/web/$site/public_html
-wget http://wordpress.org/latest.tar.gz 
-echo '===================== Dont Close this page. Installation going.... Please, wait... =========================';
-tar xfz latest.tar.gz 
-mv -f wordpress/* ./ && rmdir ./wordpress/ && rm -f latest.tar.gz 
-
-if [ -d /home/$client/web/$site/tmp ]; then echo 'wp-content Backup Exists, Restoring...';
-mv -f /home/$client/web/$site/tmp /home/$client/web/$site/public_html/ 
-rm -rf /home/$client/web/$site/tmp*
-cd /home/$client/web/$site/public_html/
-mv -f tmp/wp-content.tar.gz ./
-rm -rf /home/$client/web/$site/public_html/tmp*
-cd /home/$client/web/$site/public_html
-tar xfz wp-content.tar.gz && rm -f wp-content.tar.gz
-else
-  echo ''; fi
+	exit
+fi
 echo 'Deleting unused themes twentythirteen and twentyfourteen...';
 rm -rf /home/$client/web/$site/public_html/wp-content/themes/twentyfourteen* 
 rm -rf /home/$client/web/$site/public_html/wp-content/themes/twentythirteen* 
-
-site5="$site"
-site5digit=${site5:0:5}
-clientname="$client"
-client_=${clientname}
-
-rsync -avz /home/scripts/wp-config-sample.php /home/$client/web/$site/public_html/
-rsync -avz /home/scripts/setup-config.php /home/$client/web/$site/public_html/wp-admin/ 
-rsync -avz /home/scripts/install.php /home/$client/web/$site/public_html/wp-admin/
-find /home/$client/web/$site/public_html/wp-admin/ -name \setup-config.php -exec sed -i "s/value_wordpress/${client_}_${site5digit}/g" {} \;
-find /home/$client/web/$site/public_html/wp-admin/ -name \setup-config.php -exec sed -i "s/value_username/${client_}_${site5digit}/g" {} \;
-
-find /home/$client/web/$site/public_html/wp-admin/ -name \install.php -exec sed -i "s/value_sitetitle/$site/g" {} \;
-find /home/$client/web/$site/public_html/wp-admin/ -name \install.php -exec sed -i "s/value_username/wpadmin/g" {} \;
 
 echo 'syncing virtue_premium theme from wpmaster.bigcloudcms.com...';
 mkdir /home/$client/web/$site/public_html/wp-content/themes/virtue_premium
